# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0004_event'),
        ('taxonomy', '0004_boardpolicysection'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMeeting',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('startdate', models.DateTimeField(verbose_name='Start Date and Time')),
                ('non_district_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of Non-District Location')),
                ('non_district_location_google_place', models.URLField(blank=True, max_length=2048, null=True, verbose_name='Name of Non-District Location Google Place')),
                ('cancelled', models.BooleanField(default=False)),
                ('event_boardmeeting_node', models.OneToOneField(db_column='event_boardmeeting_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Event')),
                ('building_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events_boardmeeting_build_location', to='taxonomy.Location')),
                ('meeting_type', models.ManyToManyField(blank=True, related_name='events_boardmeeting_meeting_type', to='taxonomy.BoardMeetingType')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_boardmeeting_node', to='objects.Node')),
            ],
            options={
                'verbose_name': 'Board Meeting',
                'permissions': (('trash_boardmeeting', 'Can soft delete board meeting'), ('restore_boardmeeting', 'Can restore board meeting')),
                'get_latest_by': 'update_date',
                'default_manager_name': 'objects',
                'db_table': 'events_boardmeeting',
                'verbose_name_plural': 'Board Meetings',
            },
            bases=('objects.event',),
        ),
    ]
