# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 18:46
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone

def set_originaldate(apps,schema_editor):
    BoardMeeting = apps.get_model('events','boardmeeting')
    for item in BoardMeeting.objects.all():
        print('Setting Board Meeting:' + item.title + ' with an original date of: ' + item.startdate.strftime('%B %d, %Y @ %H:%M'))
        item.originaldate = item.startdate
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmeeting',
            name='originaldate',
            field=models.DateTimeField(default=timezone.now(), verbose_name='Original Start Date and Time'),
            preserve_default=False,
        ),
        migrations.RunPython(set_originaldate),
    ]
