# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 22:47
from __future__ import unicode_literals

from django.db import migrations, models
from apps.common.functions import currentyear

def set_schoolyear_yearend(apps,schema_editor):
    BoardMeeting = apps.get_model('events','boardmeeting')
    for item in BoardMeeting.objects.all():
        print('Setting Board Meeting:' + item.title + ' with a school year of: ' + str(currentyear(item.startdate)['currentyear']['long']) + ' and a year end of ' + str(currentyear(item.startdate)['currentyear']['short']))
        item.schoolyear = str(currentyear(item.startdate)['currentyear']['long'])
        item.yearend = str(currentyear(item.startdate)['currentyear']['short'])
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20171208_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmeeting',
            name='schoolyear',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardmeeting',
            name='yearend',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.RunPython(set_schoolyear_yearend),
    ]
