# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 21:41
from __future__ import unicode_literals

import apps.common.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20171208_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmeeting',
            name='building_location',
            field=models.ForeignKey(blank=True, default=apps.common.functions.get_district_office, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events_boardmeeting_build_location', to='taxonomy.Location'),
        ),
    ]
