# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 23:48
from __future__ import unicode_literals

import apps.common.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0005_auto_20171214_1319'),
        ('objects', '0007_faq'),
        ('events', '0005_auto_20171210_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictCalendarEvent',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('originaldate', models.DateTimeField(verbose_name='Original Start Date and Time')),
                ('startdate', models.DateTimeField(default=apps.common.functions.tomorrow_midnight, verbose_name='Start Date and Time')),
                ('enddate', models.DateTimeField(default='', verbose_name='Start Date and Time')),
                ('schoolyear', models.CharField(max_length=7)),
                ('yearend', models.CharField(max_length=4)),
                ('non_district_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of Non-District Location')),
                ('non_district_location_google_place', models.URLField(blank=True, max_length=2048, null=True, verbose_name='Name of Non-District Location Google Place')),
                ('cancelled', models.BooleanField(default=False)),
                ('districtcalendarevent_event_node', models.OneToOneField(db_column='districtcalendarevent_event_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Event')),
                ('building_location', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events_districtcalendarevent_build_location', to='taxonomy.Location')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_districtcalendarevent_node', to='objects.Node')),
            ],
            options={
                'default_manager_name': 'objects',
                'db_table': 'events_districtcalendarevent',
                'verbose_name': 'District Calendar Event',
                'verbose_name_plural': 'District Calendar Events',
                'permissions': (('trash_districtcalendarevent', 'Can soft delete district calendar event'), ('restore_districtcalendarevent', 'Can restore district calendar event')),
                'get_latest_by': 'update_date',
            },
            bases=('objects.event',),
        ),
    ]
