# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 17:49
from __future__ import unicode_literals

from django.db import migrations


def cleanup_urls(apps, schema_editor):
    DistrictCalendarEvent = apps.get_model('events','DistrictCalendarEvent')
    BoardMeeting = apps.get_model('events','BoardMeeting')

    for item in DistrictCalendarEvent.objects.all():
        print('Setting District Calendar Event: ' + item.title + ' to and originalinstance of: 1')
        item.originalinstance = 1
        item.save()

    alreadysaved = {}
    for item in BoardMeeting.objects.all().order_by('startdate'):
        count = 1
        for instance in item._meta.model.objects.filter(originaldate=item.originaldate):
            if not str(instance.pk) in alreadysaved:
                print('Setting Board Meeting: ' + item.title + ' to and originalinstance of: ' + str(count))
                instance.title
                instance.originalinstance = count
                instance.save()
                alreadysaved[str(instance.pk)] = True
                count += 1


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20171222_0803'),
    ]

    operations = [
        migrations.RunPython(cleanup_urls),
    ]
