# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 18:52
from __future__ import unicode_literals

import apps.common.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventurlcleanup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='districtcalendarevent',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'ordering': ['startdate'], 'permissions': (('trash_districtcalendarevent', 'Can soft delete district calendar event'), ('restore_districtcalendarevent', 'Can restore district calendar event')), 'verbose_name': 'District Calendar Event', 'verbose_name_plural': 'District Calendar Events'},
        ),
        migrations.AlterField(
            model_name='districtcalendarevent',
            name='startdate',
            field=models.DateTimeField(db_index=True, default=apps.common.functions.tomorrow_midnight, verbose_name='Start Date and Time'),
        ),
    ]
