# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 22:30
from __future__ import unicode_literals

import apps.common.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0006_districtcalendareventcategory'),
        ('events', '0008_auto_20171222_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtcalendarevent',
            name='event_category',
            field=models.ForeignKey(blank=True, default=apps.common.functions.get_districtcalendareventcategory_general, on_delete=django.db.models.deletion.CASCADE, related_name='events_districtcalendarevent_event_type', to='taxonomy.DistrictCalendarEventCategory'),
        ),
    ]
