# Generated by Django 2.0 on 2018-08-30 16:15

import apps.common.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_districtcalendarevent_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmeeting',
            name='building_location',
            field=models.ForeignKey(blank=True, default=apps.common.functions.get_district_office, limit_choices_to={'deleted': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events_boardmeeting_build_location', to='taxonomy.Location'),
        ),
        migrations.AlterField(
            model_name='districtcalendarevent',
            name='building_location',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'deleted': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events_districtcalendarevent_build_location', to='taxonomy.Location'),
        ),
        migrations.AlterField(
            model_name='districtcalendarevent',
            name='event_category',
            field=models.ForeignKey(blank=True, default=apps.common.functions.get_districtcalendareventcategory_general, on_delete=django.db.models.deletion.PROTECT, related_name='events_districtcalendarevent_event_type', to='taxonomy.DistrictCalendarEventCategory'),
        ),
    ]
