# Generated by Django 2.0 on 2018-09-18 16:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20180830_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardmeeting',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'permissions': (('trash_boardmeeting', 'Can soft delete board meeting'), ('restore_boardmeeting', 'Can restore board meeting')), 'verbose_name': 'Board Meeting', 'verbose_name_plural': 'Board Meetings'},
        ),
        migrations.AlterModelOptions(
            name='districtcalendarevent',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'ordering': ['startdate'], 'permissions': (('trash_districtcalendarevent', 'Can soft delete district calendar event'), ('restore_districtcalendarevent', 'Can restore district calendar event')), 'verbose_name': 'District Calendar Event', 'verbose_name_plural': 'District Calendar Events'},
        ),
        migrations.AlterModelManagers(
            name='boardmeeting',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='districtcalendarevent',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
