# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-18 16:53
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='<span>Enter the title of the site.<br>It is recommended this be the official name of the entity this site represents.</span>', max_length=200, null=True, verbose_name='Site Title')),
                ('primary_domain', models.CharField(help_text='<span>Enter the primary domain name for this site. All sites must have one primary domain that is used to access information. It is possible to have other domains used to redirect to this domain or also a development and test enviroment that does not redirect.</span>', max_length=100, null=True)),
                ('nd_statement', ckeditor.fields.RichTextField(help_text='<span>Non-Discrimination Statement is set globally for all sites and may not be editable on this page. Contact Jordan Collins if a correction may be needed.</span>', null=True, verbose_name='Non-Discrimination Statement')),
                ('ada_statement', ckeditor.fields.RichTextField(help_text='<span>Americans with Disabilities Act (ADA) Statement is set globally for all sites and may not be editable on this page. Contact Jordan Collins if a correction may be needed.</span>', null=True, verbose_name='Americans with Disabilities Act (ADA) Statement')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dashboard_general_create_user', to=settings.AUTH_USER_MODEL, to_field='uuid')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_general_site', to='sites.Site')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dashboard_general_update_user', to=settings.AUTH_USER_MODEL, to_field='uuid')),
            ],
            options={
                'db_table': 'dashboard_generalsettings',
                'verbose_name_plural': 'General Settings',
                'verbose_name': 'General Settings',
                'get_latest_by': 'update_date',
            },
        ),
    ]
