# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 14:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text=(), max_length=200, verbose_name='Template Name')),
                ('namespace', models.CharField(help_text=(), max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dashboard_template_create_user', to=settings.AUTH_USER_MODEL, to_field='uuid')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dashboard_template_update_user', to=settings.AUTH_USER_MODEL, to_field='uuid')),
            ],
            options={
                'verbose_name': 'Template',
                'get_latest_by': 'update_date',
                'db_table': 'dashboard_templates',
                'verbose_name_plural': 'Templates',
            },
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='id',
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_general_template', to='dashboard.Template'),
        ),
    ]
