# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180316_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='primary_domain',
            field=models.CharField(help_text='<p>Enter the primary domain name for this site. All sites must have one primary domain that is used to access information. It is possible to have other domains used to redirect to this domain or also a development and test enviroment that does not redirect.</p>', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_general_template', to='dashboard.Template'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='title',
            field=models.CharField(help_text='<p>Enter the title of the site.<br>It is recommended thisbe the official name of the entity this site represents.</p>', max_length=200, null=True, verbose_name='site_title'),
        ),
    ]
