# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-18 18:23
from __future__ import unicode_literals

from django.db import migrations


def create_initial_templates(apps, schema_editor):
    Template = apps.get_model('dashboard', 'template')
    User = apps.get_model('objects', 'user')
    try:
        webmaster = User.objects.get(username='webmaster@slcschools.org')
    except User.DoesNotExist:
        webmaster = None
    template, created = Template.objects.get_or_create(
        namespace='www_slcschools_org',
    )
    template.title = 'District Website'
    if created:
        template.create_user = webmaster
    template.update_user = webmaster
    template.save()
    template, created = Template.objects.get_or_create(
        namespace='material',
    )
    template.title = 'Material'
    if created:
        template.create_user = webmaster
    template.update_user = webmaster
    template.save()


def apply_default_template(apps, schema_editor):
    Template = apps.get_model('dashboard', 'template')
    try:
        material = Template.objects.get(namespace='material')
    except Template.DoesNotExist:
        material = None
    try:
        www = Template.objects.get(namespace='www_slcschools_org')
    except Template.DoesNotExist:
        www = None
    GeneralSettings = apps.get_model('dashboard', 'GeneralSettings')
    for settings in GeneralSettings.objects.all():
        if settings.site.domain == 'www.slcschools.org':
            settings.template = www
        else:
            settings.template = material
        settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180418_1222'),
    ]

    operations = [
        migrations.RunPython(create_initial_templates),
        migrations.RunPython(apply_default_template),
    ]
