# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 21:32
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180316_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='nd_statement',
            field=ckeditor.fields.RichTextField(help_text='<p>Non-Discrimination Statement is set globally for all sites and may not be editable on this page. Contact Jordan Collins if a correction may be needed.</p>', null=True, verbose_name='Non-Discrimination Statement'),
        ),
    ]
