# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-19 16:26
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_generalsettings_nd_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='ada_statement',
            field=ckeditor.fields.RichTextField(help_text='<p>Americans with Disabilities Act (ADA) Statement is set globally for all sites and may not be editable on this page. Contact Jordan Collins if a correction may be needed.</p>', null=True, verbose_name='Americans with Disabilities Act (ADA) Statement'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='title',
            field=models.CharField(help_text='<p>Enter the title of the site.<br>It is recommended this be the official name of the entity this site represents.</p>', max_length=200, null=True, verbose_name='Site Title'),
        ),
    ]
