# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-18 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_initial_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLayout',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='<span>Enter a name for this page layout. The name should be a short descriptive name for the purpose of the page (e.g. Home Page, Contact Us Page, or School Communinity Council Page).</span>', max_length=200, unique=True, verbose_name='Page Layouts')),
                ('namespace', models.CharField(help_text='<span>Enter the name of the html file that is used to render this page layout (i.e.the home page layout may have a file called home.html).</span>', max_length=200, unique=True, verbose_name='HTML File Name')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dashboard_pagelayout_create_user', to=settings.AUTH_USER_MODEL, to_field='uuid')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dashboard_pagelayout_update_user', to=settings.AUTH_USER_MODEL, to_field='uuid')),
            ],
            options={
                'verbose_name_plural': 'Page Layouts',
                'get_latest_by': 'update_date',
                'verbose_name': 'Page Layout',
                'db_table': 'dashboard_pagelayout',
            },
        ),
    ]
