# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-19 16:32
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180319_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='ada_statement',
            field=ckeditor.fields.RichTextField(help_text='<span>Americans with Disabilities Act (ADA) Statement is set globally for all sites and may not be editable on this page. Contact Jordan Collins if a correction may be needed.</span>', null=True, verbose_name='Americans with Disabilities Act (ADA) Statement'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='nd_statement',
            field=ckeditor.fields.RichTextField(help_text='<span>Non-Discrimination Statement is set globally for all sites and may not be editable on this page. Contact Jordan Collins if a correction may be needed.</span>', null=True, verbose_name='Non-Discrimination Statement'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='primary_domain',
            field=models.CharField(help_text='<span>Enter the primary domain name for this site. All sites must have one primary domain that is used to access information. It is possible to have other domains used to redirect to this domain or also a development and test enviroment that does not redirect.</span>', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='title',
            field=models.CharField(help_text='<span>Enter the title of the site.<br>It is recommended this be the official name of the entity this site represents.</span>', max_length=200, null=True, verbose_name='Site Title'),
        ),
    ]
