# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-19 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20180319_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='template',
            field=models.ForeignKey(help_text='<span>Select the template used on this site. A value must be selected.</span>', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_general_template', to='dashboard.Template', verbose_name='Template'),
        ),
    ]
