# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-15 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_initial_pagelayouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='namespace',
            field=models.CharField(help_text='<span>Enter a lower case a-z identifier for this site. Will be used to allow custom css/js files provided by the webmaster.</span>', max_length=64, null=True),
        ),
    ]
