# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-16 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_generalsettings_namespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='gatrackingid',
            field=models.CharField(blank=True, help_text='<span>Enter the Google Analytics Tracking ID for this property which can be found in the admin interface of Google Analytics.</span>', max_length=20, null=True, verbose_name='Google Analytics Tracking ID'),
        ),
    ]
