# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180319_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageLayout',
        ),
    ]
