# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0009_boardprecinct_precinct_map'),
        ('dashboard', '0008_generalsettings_gatrackingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='location',
            field=models.ForeignKey(blank=True, help_text='<span>Select the primary location for the intity this site represents. This list is managed by the webmaster.</span>', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_generalsettings_location', to='taxonomy.Location', verbose_name='Primary Location'),
        ),
    ]
