# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-17 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_generalsettings_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='main_fax',
            field=models.CharField(blank=True, help_text='<span>Enter the main fax number for the entity this site represents. The number should be in the 11 number format.  (i.e.: 18015788599)</span>', max_length=11, null=True, verbose_name='Main Fax Number'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='main_phone',
            field=models.CharField(blank=True, help_text='<span>Enter the main phone number for the entity this site represents. The number should be in the 11 number format.  (i.e.: 18015788599)</span>', max_length=11, null=True, verbose_name='Main Phone Number'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='location',
            field=models.ForeignKey(blank=True, help_text='<span>Select the primary location for the entity this site represents. This list is managed by the webmaster.</span>', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_generalsettings_location', to='taxonomy.Location', verbose_name='Primary Location'),
        ),
    ]
