# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-26 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20180517_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='monsido_domaintoken',
            field=models.CharField(blank=True, help_text='<span>Enter the Monsido Domain Token for this site which can be found in the admin interface of Monsido.</span>', max_length=30, null=True, verbose_name='Monsido Domain Token'),
        ),
    ]
