# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-28 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_sitetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelayout',
            name='allowed_sitetypes',
            field=models.ManyToManyField(blank=True, db_table='dashboard_pagelayout_allowed_sitetypes', related_name='dashboard_pagelayout_allowed_sitetypes', to='dashboard.SiteType'),
        ),
    ]
