# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-28 18:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0013_pagelayout_allowed_sitetypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTypeRequiredPage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text=('<span>Enter a name for this required page. The name should be a short descriptive name for the purpose of the page. (e.g. ', ' Home, About Our School, or School Community Council (SCC)).</span>'), max_length=200, verbose_name='Page Title')),
                ('menu_item', models.BooleanField(db_index=True, default=False, verbose_name='Include in Main Menu')),
                ('menu_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Main Menu Title')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dashboard_sitetyperequiredpage_create_user', to=settings.AUTH_USER_MODEL, to_field='uuid')),
                ('pagelayout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_sitetyperequiredpage_pagelayout', to='dashboard.PageLayout', verbose_name='Page Layout')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_sitetyperequiredpage_parent', to='dashboard.SiteTypeRequiredPage', verbose_name='Parent Page')),
                ('sitetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_sitetyperequiredpage_sitetype', to='dashboard.SiteType')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dashboard_sitetyperequiredpage_update_user', to=settings.AUTH_USER_MODEL, to_field='uuid')),
            ],
            options={
                'get_latest_by': 'update_date',
                'db_table': 'dashboard_sitetyperequiredpage',
                'verbose_name_plural': 'Site Types Required Pages',
                'verbose_name': 'Site Type Required Page',
            },
        ),
        migrations.AlterUniqueTogether(
            name='sitetyperequiredpage',
            unique_together=set([('title', 'sitetype', 'parent')]),
        ),
    ]
