# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-02 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20180628_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='sitetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_generalsettings_sitetype', to='dashboard.SiteType'),
        ),
    ]
