# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-09 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_create_pagelayouts_sitetypes_requiredpages'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='global_facebook',
            field=models.CharField(blank=True, help_text='<span>Enter the URL for the Facebook page for this site  (i.e.: https://www.facebook.com/slcschools)</span>', max_length=2000, null=True, verbose_name='Site Facebook Page'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='global_instagram',
            field=models.CharField(blank=True, help_text='<span>Enter the URL for the Instagram page for this site  (i.e.: https://www.instagram.com/slcschools/)</span>', max_length=2000, null=True, verbose_name='Site Instagram Page'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='global_twitter',
            field=models.CharField(blank=True, help_text='<span>Enter the URL for the Twitter page for this site  (i.e.: https://twitter.com/slcschools)</span>', max_length=2000, null=True, verbose_name='Site Twitter Page'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='global_youtube',
            field=models.CharField(blank=True, help_text='<span>Enter the URL for the YouTube page for this site  (i.e.: https://www.youtube.com/user/slcschools)</span>', max_length=2000, null=True, verbose_name='Site YouTube Page'),
        ),
    ]
