# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-10 21:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0017_auto_20180709_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='primary_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_generalsettings_primary_contact', to=settings.AUTH_USER_MODEL, to_field='uuid'),
        ),
    ]
