# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-23 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('dashboard', '0018_generalsettings_primary_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePublisher',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_sitepublisher_account', to=settings.AUTH_USER_MODEL, to_field='uuid')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dashboard_sitepublisher_create_user', to=settings.AUTH_USER_MODEL, to_field='uuid')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_sitepublisher_site', to='sites.Site')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dashboard_sitepublisher_update_user', to=settings.AUTH_USER_MODEL, to_field='uuid')),
            ],
            options={
                'get_latest_by': 'update_date',
                'verbose_name_plural': 'Site Publishers',
                'verbose_name': 'Site Publisher',
                'db_table': 'dashboard_sitepublisher',
            },
        ),
    ]
