# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-23 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20180823_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepublisher',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_sitepublisher_site', to='sites.Site'),
        ),
    ]
