# Generated by Django 2.0 on 2018-08-30 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20180823_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='sitetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_generalsettings_sitetype', to='dashboard.SiteType'),
        ),
        migrations.AlterField(
            model_name='sitetyperequiredpage',
            name='pagelayout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_sitetyperequiredpage_pagelayout', to='dashboard.PageLayout', verbose_name='Page Layout'),
        ),
        migrations.AlterField(
            model_name='sitetyperequiredpage',
            name='sitetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_sitetyperequiredpage_sitetype', to='dashboard.SiteType'),
        ),
    ]
