# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0009_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('your_name', models.CharField(max_length=200)),
                ('your_email', models.EmailField(max_length=254)),
                ('message_subject', models.CharField(max_length=400)),
                ('your_message', models.TextField(max_length=2000)),
                ('contactmessage_contactmessage_node', models.OneToOneField(db_column='contactmessage_contactmessage_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.ContactMessage')),
                ('inline_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactmessages_contactmessage_node', to='objects.Node')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'db_table': 'contactmessages_contactmessage',
                'default_manager_name': 'objects',
                'ordering': ['inline_order'],
                'get_latest_by': 'update_date',
                'permissions': (('trash_contactmessage', 'Can soft delete contact message'), ('restore_contactmessage', 'Can restore contact message')),
                'verbose_name_plural': 'Contact Message',
            },
            bases=('objects.contactmessage',),
        ),
    ]
