# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentbanner',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_contentbanner', 'Can soft delete content banner'), ('restore_contentbanner', 'Can restore content banner')), 'verbose_name': 'Content Banner', 'verbose_name_plural': 'Content Banners'},
        ),
        migrations.AlterModelOptions(
            name='pagebanner',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_pagebanner', 'Can soft delete page banner'), ('restore_pagebanner', 'Can restore page banner')), 'verbose_name': 'Page Banner', 'verbose_name_plural': 'Page Banners'},
        ),
        migrations.AlterModelOptions(
            name='thumbnail',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_thumbnail', 'Can soft delete thumbnail'), ('restore_thumbnail', 'Can restore thumbnail')), 'verbose_name': 'Thumbnail', 'verbose_name_plural': 'Thumbnails'},
        ),
        migrations.AlterModelManagers(
            name='contentbanner',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='pagebanner',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='thumbnail',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='contentbanner',
            name='related_node',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_contentbanner_node', to='objects.Node'),
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='related_node',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_pagebanner_node', to='objects.Node'),
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='related_node',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_thumbnail_node', to='objects.Node'),
        ),
    ]
