# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 18:48
from __future__ import unicode_literals

import apps.common.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
        ('images', '0002_auto_20171108_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsThumbnail',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('image_file', models.ImageField(max_length=2000, upload_to=apps.common.functions.image_upload_to, verbose_name='Image')),
                ('alttext', models.CharField(max_length=200, verbose_name='Alternative Text')),
                ('newsthumbnail_image_node', models.OneToOneField(db_column='newsthumbnail_image_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Image')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_newsthumbnail_node', to='objects.Node')),
            ],
            options={
                'permissions': (('trash_newsthumbnail', 'Can soft delete news thumbnail'), ('restore_thumbnail', 'Can restore news thumbnail')),
                'verbose_name': 'News Thumbnail',
                'db_table': 'images_newsthumbnail',
                'get_latest_by': 'update_date',
                'verbose_name_plural': 'News Thumbnails',
                'default_manager_name': 'objects',
            },
            bases=('objects.image',),
        ),
    ]
