# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 17:03
from __future__ import unicode_literals

import apps.common.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_node_has_permissions'),
        ('images', '0003_newsthumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('image_file', models.ImageField(max_length=2000, upload_to=apps.common.functions.image_upload_to, verbose_name='Image')),
                ('alttext', models.CharField(max_length=200, verbose_name='Alternative Text')),
                ('profilepicture_image_node', models.OneToOneField(db_column='profilepicture_image_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Image')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_profilepicture_node', to='objects.Node')),
            ],
            options={
                'db_table': 'images_profilepicture',
                'permissions': (('trash_profilepicture', 'Can soft delete profile picture'), ('restore_profilepicture', 'Can restore profile picture')),
                'get_latest_by': 'update_date',
                'default_manager_name': 'objects',
                'verbose_name': 'Profile Picture',
                'verbose_name_plural': 'Profile Pictures',
            },
            bases=('objects.image',),
        ),
    ]
