# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 19:38
from __future__ import unicode_literals

import apps.common.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0015_data_slug_sluginstance'),
        ('images', '0006_districtlogos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('photogallery_image_node', models.OneToOneField(db_column='photogallery_image_node', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='objects.Image')),
                ('inline_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('related_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_photogallery_node', to='objects.Node')),
            ],
            options={
                'ordering': ['inline_order'],
                'verbose_name_plural': 'Photo Galleries',
                'db_table': 'images_photogallery',
                'verbose_name': 'Photo Gallery',
                'permissions': (('trash_photogallery', 'Can soft delete photo gallery'), ('restore_photogallery', 'Can restore photo gallery')),
                'get_latest_by': 'update_date',
                'default_manager_name': 'objects',
            },
            bases=('objects.image',),
        ),
        migrations.CreateModel(
            name='PhotoGalleryImage',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('image_file', models.ImageField(max_length=2000, upload_to=apps.common.functions.image_upload_to, verbose_name='Image')),
                ('alttext', models.CharField(max_length=200, verbose_name='Alternative Text')),
                ('photogallery_image_node', models.OneToOneField(db_column='photogalleryimage_image_node', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='objects.Image')),
                ('inline_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('related_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_photogalleryimage_node', to='objects.Node')),
            ],
            options={
                'ordering': ['inline_order'],
                'verbose_name_plural': 'Photo Gallery Images',
                'db_table': 'images_photogalleryimage',
                'verbose_name': 'Photo Gallery Image',
                'permissions': (('trash_photogalleryimage', 'Can soft delete photo gallery image'), ('restore_photogalleryimage', 'Can restore photo gallery image')),
                'get_latest_by': 'update_date',
                'default_manager_name': 'objects',
            },
            bases=('objects.image',),
        ),
    ]
