# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-18 19:34
from __future__ import unicode_literals

import apps.common.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0018_auto_20180419_1349'),
        ('images', '0007_photogallery_photogalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InlineImage',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('image_file', models.ImageField(max_length=2000, upload_to=apps.common.functions.image_upload_to, verbose_name='Image')),
                ('inlineimage_image_node', models.OneToOneField(db_column='inlineimage_image_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Image')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_inlineimage_node', to='objects.Node')),
            ],
            options={
                'permissions': (('trash_inlineimage', 'Can soft delete inline image'), ('restore_inlineimage', 'Can restore inline image')),
                'verbose_name_plural': 'Inline Images',
                'verbose_name': 'Inline Image',
                'db_table': 'images_inlineimage',
                'get_latest_by': 'update_date',
                'default_manager_name': 'objects',
            },
            bases=('objects.image',),
        ),
    ]
