# Generated by Django 2.0 on 2018-08-30 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_inlineimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtlogo',
            name='district_logo_group',
            field=models.ForeignKey(limit_choices_to={'deleted': False, 'published': True}, on_delete=django.db.models.deletion.PROTECT, related_name='images_districtlogo_district_logo_group', to='taxonomy.DistrictLogoGroup', verbose_name='District Logo Group'),
        ),
        migrations.AlterField(
            model_name='districtlogo',
            name='district_logo_style_variation',
            field=models.ForeignKey(limit_choices_to={'deleted': False, 'published': True}, on_delete=django.db.models.deletion.PROTECT, related_name='images_districtlogo_district_logo_style_variation', to='taxonomy.DistrictLogoStyleVariation', verbose_name='District Logo Style Variation'),
        ),
        migrations.AlterField(
            model_name='districtlogo',
            name='districtlogo_image_node',
            field=models.OneToOneField(db_column='districtlogo_image_node', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Image'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='photogallery_image_node',
            field=models.OneToOneField(db_column='photogallery_image_node', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Image'),
        ),
        migrations.AlterField(
            model_name='photogalleryimage',
            name='photogallery_image_node',
            field=models.OneToOneField(db_column='photogalleryimage_image_node', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Image'),
        ),
    ]
