# Generated by Django 2.0 on 2018-09-18 16:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_auto_20180830_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentbanner',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'ordering': ['inline_order'], 'permissions': (('trash_contentbanner', 'Can soft delete content banner'), ('restore_contentbanner', 'Can restore content banner')), 'verbose_name': 'Content Banner', 'verbose_name_plural': 'Content Banners'},
        ),
        migrations.AlterModelOptions(
            name='districtlogo',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'permissions': (('trash_districtlogo', 'Can soft delete district logo'), ('restore_districtlogo', 'Can restore district logo')), 'verbose_name': 'District Logo', 'verbose_name_plural': 'District Logos'},
        ),
        migrations.AlterModelOptions(
            name='districtlogogif',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'permissions': (('trash_districtlogogif', 'Can soft delete district logo gif'), ('restore_districtlogogif', 'Can restore district logo gif')), 'verbose_name': 'District Logo GIF', 'verbose_name_plural': 'District Logo GIFs'},
        ),
        migrations.AlterModelOptions(
            name='districtlogojpg',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'permissions': (('trash_districtlogojpg', 'Can soft delete district logo jpg'), ('restore_districtlogojpg', 'Can restore district logo jpg')), 'verbose_name': 'District Logo JPG', 'verbose_name_plural': 'District Logo JPGs'},
        ),
        migrations.AlterModelOptions(
            name='districtlogopng',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'permissions': (('trash_districtlogopng', 'Can soft delete district logo png'), ('restore_districtlogopng', 'Can restore district logo png')), 'verbose_name': 'District Logo PNG', 'verbose_name_plural': 'District Logo PNGs'},
        ),
        migrations.AlterModelOptions(
            name='districtlogotif',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'permissions': (('trash_districtlogotif', 'Can soft delete district logo tif'), ('restore_districtlogotif', 'Can restore district logo tif')), 'verbose_name': 'District Logo TIF', 'verbose_name_plural': 'District Logo TIFs'},
        ),
        migrations.AlterModelOptions(
            name='inlineimage',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'permissions': (('trash_inlineimage', 'Can soft delete inline image'), ('restore_inlineimage', 'Can restore inline image')), 'verbose_name': 'Inline Image', 'verbose_name_plural': 'Inline Images'},
        ),
        migrations.AlterModelOptions(
            name='newsthumbnail',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'permissions': (('trash_newsthumbnail', 'Can soft delete news thumbnail'), ('restore_thumbnail', 'Can restore news thumbnail')), 'verbose_name': 'News Thumbnail', 'verbose_name_plural': 'News Thumbnails'},
        ),
        migrations.AlterModelOptions(
            name='pagebanner',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'permissions': (('trash_pagebanner', 'Can soft delete page banner'), ('restore_pagebanner', 'Can restore page banner')), 'verbose_name': 'Page Banner', 'verbose_name_plural': 'Page Banners'},
        ),
        migrations.AlterModelOptions(
            name='photogallery',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'ordering': ['inline_order'], 'permissions': (('trash_photogallery', 'Can soft delete photo gallery'), ('restore_photogallery', 'Can restore photo gallery')), 'verbose_name': 'Photo Gallery', 'verbose_name_plural': 'Photo Galleries'},
        ),
        migrations.AlterModelOptions(
            name='photogalleryimage',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'ordering': ['inline_order'], 'permissions': (('trash_photogalleryimage', 'Can soft delete photo gallery image'), ('restore_photogalleryimage', 'Can restore photo gallery image')), 'verbose_name': 'Photo Gallery Image', 'verbose_name_plural': 'Photo Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='profilepicture',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'permissions': (('trash_profilepicture', 'Can soft delete profile picture'), ('restore_profilepicture', 'Can restore profile picture')), 'verbose_name': 'Profile Picture', 'verbose_name_plural': 'Profile Pictures'},
        ),
        migrations.AlterModelOptions(
            name='thumbnail',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'permissions': (('trash_thumbnail', 'Can soft delete thumbnail'), ('restore_thumbnail', 'Can restore thumbnail')), 'verbose_name': 'Thumbnail', 'verbose_name_plural': 'Thumbnails'},
        ),
        migrations.AlterModelManagers(
            name='contentbanner',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='districtlogo',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='districtlogogif',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='districtlogojpg',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='districtlogopng',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='districtlogotif',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='inlineimage',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='newsthumbnail',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='pagebanner',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='photogallery',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='photogalleryimage',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='profilepicture',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='thumbnail',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
