# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 06:56
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0007_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=2000)),
                ('answer', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('faq_faq_node', models.OneToOneField(db_column='faq_faq_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.FAQ')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs_faq_node', to='objects.Node')),
            ],
            options={
                'verbose_name': 'Fequently Asked Question',
                'db_table': 'faqs_faq',
                'verbose_name_plural': 'Frequently Asked Questions',
                'get_latest_by': 'update_date',
                'permissions': (('trash_faq', 'Can soft delete faq'), ('restore_faq', 'Can restore faq')),
                'default_manager_name': 'objects',
            },
            bases=('objects.faq',),
        ),
    ]
