# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'ordering': ['inline_order'], 'permissions': (('trash_faq', 'Can soft delete faq'), ('restore_faq', 'Can restore faq')), 'verbose_name': 'Fequently Asked Question', 'verbose_name_plural': 'Frequently Asked Questions'},
        ),
        migrations.AddField(
            model_name='faq',
            name='inline_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
