# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('link_url', models.CharField(db_index=True, max_length=2000, unique=True)),
                ('resourcelink_link_node', models.OneToOneField(db_column='resourcelink_link_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Link')),
                ('related_nodes', models.ManyToManyField(related_name='links_resourcelink_node', to='objects.Node')),
            ],
            options={
                'verbose_name_plural': 'Resource Links',
                'db_table': 'links_resourcelink',
                'verbose_name': 'Resource Link',
                'permissions': (('trash_resourcelink', 'Can soft delete resource link'), ('restore_resourcelink', 'Can restore resource link')),
                'get_latest_by': 'update_date',
            },
            bases=('objects.link',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
