# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_auto_20171210_1447'),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionButton',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('link_url', models.CharField(db_index=True, max_length=2000, unique=True)),
                ('actionbutton_link_node', models.OneToOneField(db_column='actionbutton_link_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Link')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links_actionbutton_node', to='objects.Node')),
            ],
            options={
                'db_table': 'links_actionbutton',
                'get_latest_by': 'update_date',
                'verbose_name': 'Action Button',
                'verbose_name_plural': 'Action Buttons',
                'permissions': (('trash_actionbutton', 'Can soft delete action button'), ('restore_resourcelink', 'Can restore action button')),
            },
            bases=('objects.link',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
