# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_actionbutton'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionbutton',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_actionbutton', 'Can soft delete action button'), ('restore_resourcelink', 'Can restore action button')), 'verbose_name': 'Action Button', 'verbose_name_plural': 'Action Buttons'},
        ),
        migrations.AlterModelManagers(
            name='actionbutton',
            managers=[
            ],
        ),
    ]
