# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 19:25
from __future__ import unicode_literals

from django.db import migrations, models

def set_inline_order(apps,schema_editor):
    ActionButton = apps.get_model('links','actionbutton')
    for index, item in enumerate(ActionButton.objects.all()):
        print('Setting ' + item.title + ' to an index of ' + str(index + 1))
        item.inline_order = index + 1
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20171213_0936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionbutton',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'ordering': ['inline_order'], 'permissions': (('trash_actionbutton', 'Can soft delete action button'), ('restore_resourcelink', 'Can restore action button')), 'verbose_name': 'Action Button', 'verbose_name_plural': 'Action Buttons'},
        ),
        migrations.AddField(
            model_name='actionbutton',
            name='inline_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(set_inline_order),
    ]
