# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_auto_20171214_1319'),
        ('links', '0006_remove_resourcelink_related_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelink',
            name='related_node',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links_resourcelink_node', to='objects.Node'),
        ),
    ]
