# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0008_auto_20171214_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionbutton',
            name='link_url',
            field=models.CharField(db_index=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='resourcelink',
            name='link_url',
            field=models.CharField(db_index=True, max_length=2000),
        ),
    ]
