# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-06 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0009_auto_20171214_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelink',
            name='related_locked',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
