# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-07 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0010_resourcelink_related_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelink',
            name='related_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
