# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-07 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0011_resourcelink_related_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelink',
            name='modal_ajax',
            field=models.BooleanField(default=False),
        ),
    ]
