# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-29 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0021_node_section_page_count'),
        ('links', '0013_resourcelink_target_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassWebsite',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='Class Name')),
                ('link_url', models.CharField(db_index=True, max_length=2000)),
                ('classwebsite_link_node', models.OneToOneField(db_column='classwebsite_link_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Link')),
                ('inline_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links_classwebsite_node', to='objects.Node')),
            ],
            options={
                'verbose_name_plural': 'Class Websites',
                'db_table': 'links_classwebsite',
                'get_latest_by': 'update_date',
                'ordering': ['inline_order'],
                'permissions': (('trash_classwebsite', 'Can soft delete class website'), ('restore_resourcelink', 'Can restore class website')),
                'default_manager_name': 'objects',
                'verbose_name': 'Class Website',
            },
            bases=('objects.link',),
        ),
    ]
