# Generated by Django 2.0 on 2018-09-18 16:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0014_classwebsite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionbutton',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'ordering': ['inline_order'], 'permissions': (('trash_actionbutton', 'Can soft delete action button'), ('restore_resourcelink', 'Can restore action button')), 'verbose_name': 'Action Button', 'verbose_name_plural': 'Action Buttons'},
        ),
        migrations.AlterModelOptions(
            name='classwebsite',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'ordering': ['inline_order'], 'permissions': (('trash_classwebsite', 'Can soft delete class website'), ('restore_resourcelink', 'Can restore class website')), 'verbose_name': 'Class Website', 'verbose_name_plural': 'Class Websites'},
        ),
        migrations.AlterModelOptions(
            name='resourcelink',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'ordering': ['inline_order'], 'permissions': (('trash_resourcelink', 'Can soft delete resource link'), ('restore_resourcelink', 'Can restore resource link')), 'verbose_name': 'Resource Link', 'verbose_name_plural': 'Resource Links'},
        ),
        migrations.AlterModelManagers(
            name='actionbutton',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='classwebsite',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='resourcelink',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
