# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('document_document_node', models.OneToOneField(db_column='document_document_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Document')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_document_node', to='objects.Node')),
            ],
            options={
                'verbose_name_plural': 'Documents',
                'db_table': 'documents_document',
                'verbose_name': 'Document',
                'permissions': (('trash_document', 'Can soft delete document'), ('restore_document', 'Can restore document')),
                'get_latest_by': 'update_date',
            },
            bases=('objects.document',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
