# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_node_has_permissions'),
        ('taxonomy', '0004_boardpolicysection'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPolicy',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('policy_title', models.CharField(max_length=150, unique=True, verbose_name='Policy Title')),
                ('index', models.IntegerField(verbose_name='Policy Section Number')),
                ('document_boardpolicy_node', models.OneToOneField(db_column='document_boardpolicy_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Document')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_boardpolicy_node', to='objects.Node')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_boardpolicy_section', to='taxonomy.BoardPolicySection')),
            ],
            options={
                'verbose_name': 'Board Policy',
                'verbose_name_plural': 'Board Policies',
                'get_latest_by': 'update_date',
                'db_table': 'documents_boardpolicy',
                'permissions': (('trash_boardpolicy', 'Can soft delete board policy'), ('restore_boardpolicy', 'Can restore board policy')),
            },
            bases=('objects.document',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
