# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_auto_20171210_1447'),
        ('documents', '0004_supportingdocument_document_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMeetingAgenda',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('document_boardmeetingagenda_node', models.OneToOneField(db_column='document_boardmeetingagenda_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Document')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_boardmeetingagenda_node', to='objects.Node')),
            ],
            options={
                'verbose_name_plural': 'Board Meeting Agendas',
                'get_latest_by': 'update_date',
                'permissions': (('trash_boardmeetingagenda', 'Can soft delete board meeting agenda'), ('restore_boardmeetingagenda', 'Can restore board meeting agenda')),
                'db_table': 'documents_boardmeetingagenda',
                'verbose_name': 'Board Meeting Agenda',
                'default_manager_name': 'objects',
            },
            bases=('objects.document',),
        ),
        migrations.CreateModel(
            name='BoardMeetingMinutes',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('document_boardmeetingminutes_node', models.OneToOneField(db_column='document_boardmeetingminutes_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Document')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_boardmeetingminutes_node', to='objects.Node')),
            ],
            options={
                'verbose_name_plural': 'Board Meeting Minutes',
                'get_latest_by': 'update_date',
                'permissions': (('trash_boardmeetingminutes', 'Can soft delete board meeting minutes'), ('restore_boardmeetingminutes', 'Can restore board meeting minutes')),
                'db_table': 'documents_boardmeetingminutes',
                'verbose_name': 'Board Meeting Minutes',
                'default_manager_name': 'objects',
            },
            bases=('objects.document',),
        ),
    ]
