# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_auto_20171210_1447'),
        ('documents', '0005_boardmeetingagenda_boardmeetingminutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMeetingAudio',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('boardmeetingaudio_document_node', models.OneToOneField(db_column='boardmeetingaudio_document_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Document')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_boardmeetingaudio_node', to='objects.Node')),
            ],
            options={
                'permissions': (('trash_boardmeetingaudio', 'Can soft delete board meeting audio'), ('restore_boardmeetingaudio', 'Can restore board meeting audio')),
                'verbose_name_plural': 'Board Meeting Audio',
                'default_manager_name': 'objects',
                'db_table': 'documents_boardmeetingaudio',
                'get_latest_by': 'update_date',
                'verbose_name': 'Board Meeting Audio',
            },
            bases=('objects.document',),
        ),
        migrations.CreateModel(
            name='BoardMeetingVideo',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('boardmeetingvideo_document_node', models.OneToOneField(db_column='boardmeetingvideo_document_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Document')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_boardmeetingvideo_node', to='objects.Node')),
            ],
            options={
                'permissions': (('trash_boardmeetingvideo', 'Can soft delete board meeting video'), ('restore_boardmeetingvideo', 'Can restore board meeting video')),
                'verbose_name_plural': 'Board Meeting Videos',
                'default_manager_name': 'objects',
                'db_table': 'documents_boardmeetingvideo',
                'get_latest_by': 'update_date',
                'verbose_name': 'Board Meeting Video',
            },
            bases=('objects.document',),
        ),
    ]
