# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_auto_20171210_1447'),
        ('documents', '0006_boardmeetingaudio_boardmeetingvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMeetingAgendaItem',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('boardmeetingagendaitem_document_node', models.OneToOneField(db_column='boardmeetingagendaitem_document_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Document')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_boardmeetingagendaitem_node', to='objects.Node')),
            ],
            options={
                'permissions': (('trash_boardmeetingagendaitem', 'Can soft delete board meeting agenda item'), ('restore_boardmeetingagendaitem', 'Can restore board meeting agenda item')),
                'verbose_name': 'Board Meeting Agenda Item',
                'get_latest_by': 'update_date',
                'db_table': 'documents_boardmeetingagendaitem',
                'verbose_name_plural': 'Board Meeting Agenda Items',
                'default_manager_name': 'objects',
            },
            bases=('objects.document',),
        ),
        migrations.CreateModel(
            name='BoardMeetingExhibit',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('boardmeetingexhibit_document_node', models.OneToOneField(db_column='boardmeetingexhibit_document_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Document')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_boardmeetingexhibit_node', to='objects.Node')),
            ],
            options={
                'permissions': (('trash_boardmeetingexhibit', 'Can soft delete board meeting exhibit'), ('restore_boardmeetingexhibit', 'Can restore board meeting exhibit')),
                'verbose_name': 'Board Meeting Exhibit',
                'get_latest_by': 'update_date',
                'db_table': 'documents_boardmeetingexhibit',
                'verbose_name_plural': 'Board Meeting Exhibits',
                'default_manager_name': 'objects',
            },
            bases=('objects.document',),
        ),
    ]
