# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20171214_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardpolicy',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_boardpolicy', 'Can soft delete board policy'), ('restore_boardpolicy', 'Can restore board policy')), 'verbose_name': 'Board Policy', 'verbose_name_plural': 'Board Policies'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'ordering': ['inline_order'], 'permissions': (('trash_document', 'Can soft delete document'), ('restore_document', 'Can restore document')), 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelManagers(
            name='boardpolicy',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='document',
            managers=[
            ],
        ),
    ]
