# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20171214_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpolicy',
            name='boardmeeting_review',
            field=models.DateField(blank=True, null=True, verbose_name='Anticipated Board Meeting Review'),
        ),
        migrations.AddField(
            model_name='boardpolicy',
            name='last_approved',
            field=models.DateField(blank=True, null=True, verbose_name='Last Approved'),
        ),
        migrations.AddField(
            model_name='boardpolicy',
            name='subcommittee_review',
            field=models.DateField(blank=True, null=True, verbose_name='Subcommitte Meeting Review'),
        ),
    ]
