# Generated by Django 2.0 on 2018-08-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_disclosuredocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclosuredocument',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Class Name'),
        ),
    ]
