# Generated by Django 2.0 on 2018-09-26 16:28

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0024_auto_20180918_1055'),
        ('documents', '0013_auto_20180918_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCommunityCouncilMeetingAgenda',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('schoolcommunitycouncilmeetingagenda_document_node', models.OneToOneField(db_column='sccagenda_schoolcommunitycouncilmeetingagenda_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Document')),
                ('inline_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_schoolcommunitycouncilmeetingagenda_node', to='objects.Node')),
            ],
            options={
                'permissions': (('trash_schoolcommunitycouncilmeetingagenda', 'Can soft delete scc agenda'), ('restore_schoolcommunitycouncilmeetingagenda', 'Can restore scc agenda')),
                'default_manager_name': 'base_manager',
                'get_latest_by': 'update_date',
                'ordering': ['inline_order'],
                'verbose_name': 'School Community Council Meeting Agenda',
                'db_table': 'documents_schoolcommunitycouncilmeetingagenda',
                'verbose_name_plural': 'School Community Council Meeting Agendas',
            },
            bases=('objects.document',),
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolCommunityCouncilMeetingMinutes',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('schoolcommunitycouncilmeetingminutes_document_node', models.OneToOneField(db_column='sccMinutes_schoolcommunitycouncilmeetingminutes_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Document')),
                ('inline_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_schoolcommunitycouncilmeetingminutes_node', to='objects.Node')),
            ],
            options={
                'permissions': (('trash_schoolcommunitycouncilmeetingminutes', 'Can soft delete scc minutes'), ('restore_schoolcommunitycouncilmeetingminutes', 'Can restore scc minutes')),
                'default_manager_name': 'base_manager',
                'get_latest_by': 'update_date',
                'ordering': ['inline_order'],
                'verbose_name': 'School Community Council Meeting Minutes',
                'db_table': 'documents_schoolcommunitycouncilmeetingminutes',
                'verbose_name_plural': 'School Community Council Meeting Minutes',
            },
            bases=('objects.document',),
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
