# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 05:33
from __future__ import unicode_literals

from django.db import migrations, models

def set_user_title(apps, schema_editor):
    Employee = apps.get_model('users','employee')
    System = apps.get_model('users','system')
    for employee in Employee.objects.all():
        employee.save()
    for system in System.objects.all():
        system.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employee_non_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.RunPython(set_user_title),
    ]
