# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-31 21:34
from __future__ import unicode_literals

from django.db import migrations


def set_user_title(apps, schema_editor):
    Employee = apps.get_model('users','employee')
    System = apps.get_model('users','system')
    for employee in Employee.objects.all():
        employee.title = employee.force_title()
        employee.save()
    for system in System.objects.all():
        system.title = system.force_title()
        system.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180125_2233'),
    ]

    operations = [
        migrations.RunPython(set_user_title),
    ]
