# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180125_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='system',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
