# Generated by Django 2.0 on 2018-09-12 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0023_auto_20180830_1405'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_auto_20180830_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageEditor',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='objects_pageeditor_create_user', to=settings.AUTH_USER_MODEL, to_field='uuid')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_pageeditor_employee', to='users.Employee')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_pageeditor_node', to='objects.Node')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='objects_pageeditor_update_user', to=settings.AUTH_USER_MODEL, to_field='uuid')),
            ],
            options={
                'get_latest_by': 'create_date',
                'verbose_name_plural': 'Page Editors',
                'verbose_name': 'Page Editor',
                'db_table': 'users_pageeditor',
            },
        ),
    ]
