# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
        ('directoryentries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladministrator',
            name='related_node',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directoryentries_schooladministrator_node', to='objects.Node'),
        ),
    ]
