# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directoryentries', '0002_schooladministrator_related_node'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooladministrator',
            options={'default_manager_name': 'objects', 'get_latest_by': 'create_date', 'verbose_name': 'School Administrator', 'verbose_name_plural': 'School Administrators'},
        ),
        migrations.AlterModelManagers(
            name='schooladministrator',
            managers=[
            ],
        ),
    ]
