# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryentries', '0004_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='job_title',
            field=models.CharField(default='Employee', max_length=200),
            preserve_default=False,
        ),
    ]
