# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_node_has_permissions'),
        ('taxonomy', '0002_boardprecinct'),
        ('users', '0003_employee_in_directory'),
        ('directoryentries', '0005_staff_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('street_address', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('boardmember_directoryentry_node', models.OneToOneField(db_column='boardmember_directoryentry_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.DirectoryEntry')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directoryenties_boardmember_city', to='taxonomy.City')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directoryenties_boardmember_employee', to='users.Employee')),
                ('precinct', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directoryenties_boardmember_precinct', to='taxonomy.BoardPrecinct')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directoryentries_boardmember_node', to='objects.Node')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directoryenties_boardmember_state', to='taxonomy.State')),
                ('zipcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directoryenties_boardmember_zipcode', to='taxonomy.Zipcode')),
            ],
            options={
                'db_table': 'directoryenties_boardmember',
                'get_latest_by': 'create_date',
                'verbose_name': 'Board Member',
                'verbose_name_plural': 'Board Members',
                'default_manager_name': 'objects',
            },
            bases=('objects.directoryentry',),
        ),
    ]
