# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_node_has_permissions'),
        ('taxonomy', '0003_boardmeetingtype'),
        ('directoryentries', '0006_boardmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBoardMember',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=11)),
                ('studentboardmember_directoryentry_node', models.OneToOneField(db_column='studentboardmember_directoryentry_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.DirectoryEntry')),
                ('building_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directoryentries_studentboardmember_building_location', to='taxonomy.Location')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directoryentries_studentboardmember_node', to='objects.Node')),
            ],
            options={
                'verbose_name_plural': 'Student Board Members',
                'default_manager_name': 'objects',
                'db_table': 'directoryenties_studentboardmember',
                'verbose_name': 'Student Board Member',
                'get_latest_by': 'create_date',
            },
            bases=('objects.directoryentry',),
        ),
    ]
