# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directoryentries', '0007_studentboardmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentboardmember',
            name='building_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directoryentries_studentboardmember_building_location', to='taxonomy.Location'),
        ),
        migrations.AlterField(
            model_name='studentboardmember',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='studentboardmember',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='studentboardmember',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
