# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_node_has_permissions'),
        ('users', '0004_employee_non_employee'),
        ('directoryentries', '0008_auto_20171204_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPolicyAdmin',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('boardpolicyadmin_directoryentry_node', models.OneToOneField(db_column='boardpolicyadmin_directoryentry_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.DirectoryEntry')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directoryenties_boardpolicyadmin_employee', to='users.Employee')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directoryentries_boardpolicyadmin_node', to='objects.Node')),
            ],
            options={
                'default_manager_name': 'objects',
                'db_table': 'directoryenties_boardpolicyadmin',
                'verbose_name': 'Board Policy Administrator',
                'verbose_name_plural': 'Board Policy Administrators',
                'get_latest_by': 'create_date',
            },
            bases=('objects.directoryentry',),
        ),
    ]
