# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employee_non_employee'),
        ('objects', '0005_auto_20171210_1447'),
        ('directoryentries', '0009_boardpolicyadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('administrator_directoryentry_node', models.OneToOneField(db_column='administrator_directoryentry_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.DirectoryEntry')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directoryenties_administrator_employee', to='users.Employee')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directoryentries_administrator_node', to='objects.Node')),
            ],
            options={
                'default_manager_name': 'objects',
                'db_table': 'directoryenties_administrator',
                'get_latest_by': 'create_date',
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administrators',
            },
            bases=('objects.directoryentry',),
        ),
    ]
