# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 17:29
from __future__ import unicode_literals

from django.db import migrations, models

def set_inline_order(apps,schema_editor):
    Administrator = apps.get_model('directoryentries','administrator')
    for index, item in enumerate(Administrator.objects.all()):
        print('Setting ' + item.title + ' to an index of ' + str(index + 1))
        item.inline_order = index + 1
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('directoryentries', '0011_administrator_job_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'default_manager_name': 'objects', 'get_latest_by': 'create_date', 'ordering': ['inline_order'], 'verbose_name': 'Administrator', 'verbose_name_plural': 'Administrators'},
        ),
        migrations.AddField(
            model_name='administrator',
            name='inline_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(set_inline_order), 
    ]
