# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryentries', '0013_auto_20171214_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
