# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryentries', '0014_auto_20171218_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooladministrator',
            options={'default_manager_name': 'objects', 'get_latest_by': 'create_date', 'ordering': ['inline_order'], 'verbose_name': 'School Administrator', 'verbose_name_plural': 'School Administrators'},
        ),
        migrations.AddField(
            model_name='schooladministrator',
            name='inline_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
