# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 22:27
from __future__ import unicode_literals

import apps.common.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryentries', '0016_auto_20180309_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='term_ends',
            field=models.DateTimeField(blank=True, default=apps.common.functions.december_thirty_first, null=True, verbose_name='Term Ends'),
        ),
    ]
