# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-12 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0020_auto_20180711_0613'),
        ('users', '0007_auto_20180125_2248'),
        ('directoryentries', '0017_boardmember_term_ends'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAdministration',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('schooladministration_directoryentry_node', models.OneToOneField(db_column='schooladministration_directoryentry_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.DirectoryEntry')),
                ('inline_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directoryenties_schooladministration_employee', to='users.Employee')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directoryentries_schooladministration_node', to='objects.Node')),
            ],
            options={
                'verbose_name_plural': 'School Administration',
                'db_table': 'directoryenties_schooladministration',
                'ordering': ['inline_order'],
                'verbose_name': 'School Administrator',
                'default_manager_name': 'objects',
                'get_latest_by': 'create_date',
            },
            bases=('objects.directoryentry',),
        ),
        migrations.CreateModel(
            name='SchoolStaff',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('schoolstaff_directoryentry_node', models.OneToOneField(db_column='schoolstaff_directoryentry_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.DirectoryEntry')),
                ('inline_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directoryenties_schoolstaff_employee', to='users.Employee')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directoryentries_schoolstaff_node', to='objects.Node')),
            ],
            options={
                'verbose_name_plural': 'School Staff',
                'db_table': 'directoryenties_schoolstaff',
                'ordering': ['inline_order'],
                'verbose_name': 'School Staff',
                'default_manager_name': 'objects',
                'get_latest_by': 'create_date',
            },
            bases=('objects.directoryentry',),
        ),
    ]
