# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-22 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180125_2248'),
        ('objects', '0020_auto_20180711_0613'),
        ('directoryentries', '0018_schooladministration_schoolstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFaculty',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('schoolfaculty_directoryentry_node', models.OneToOneField(db_column='schoolfaculty_directoryentry_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.DirectoryEntry')),
                ('inline_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directoryenties_schoolfaculty_employee', to='users.Employee')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directoryentries_schoolfaculty_node', to='objects.Node')),
            ],
            options={
                'db_table': 'directoryenties_schoolfaculty',
                'verbose_name': 'School Faculty',
                'verbose_name_plural': 'School Faculty',
                'get_latest_by': 'create_date',
                'ordering': ['inline_order'],
                'default_manager_name': 'objects',
            },
            bases=('objects.directoryentry',),
        ),
    ]
