# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-22 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0012_subjectgradelevel'),
        ('directoryentries', '0019_schoolfaculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfaculty',
            name='additional_subjects',
            field=models.ManyToManyField(blank=True, related_name='directoryenties_schoolfaculty_additional_subjects', to='taxonomy.SubjectGradeLevel', verbose_name='Additional Subjects'),
        ),
        migrations.AddField(
            model_name='schoolfaculty',
            name='primary_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directoryenties_schoolfaculty_primary_subject', to='taxonomy.SubjectGradeLevel'),
        ),
    ]
