# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-22 16:37
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directoryentries', '0020_auto_20180822_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladministration',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About Me'),
        ),
        migrations.AddField(
            model_name='schoolfaculty',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About Me'),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About Me'),
        ),
    ]
