# Generated by Django 2.0 on 2018-08-30 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directoryentries', '0021_auto_20180822_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='city',
            field=models.ForeignKey(blank=True, limit_choices_to={'deleted': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directoryenties_boardmember_city', to='taxonomy.City'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='state',
            field=models.ForeignKey(blank=True, limit_choices_to={'deleted': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directoryenties_boardmember_state', to='taxonomy.State'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='zipcode',
            field=models.ForeignKey(blank=True, limit_choices_to={'deleted': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directoryenties_boardmember_zipcode', to='taxonomy.Zipcode'),
        ),
        migrations.AlterField(
            model_name='studentboardmember',
            name='building_location',
            field=models.ForeignKey(blank=True, limit_choices_to={'deleted': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directoryentries_studentboardmember_building_location', to='taxonomy.Location'),
        ),
    ]
