# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 20:23
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
        ('taxonomy', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('title', models.CharField(db_index=True, max_length=200, unique=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Short Description')),
                ('main_phone', models.CharField(max_length=11)),
                ('main_fax', models.CharField(max_length=11)),
                ('department_page_node', models.OneToOneField(db_column='department_page_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Page')),
                ('building_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages_department_building_location', to='taxonomy.Location')),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'verbose_name': 'Department',
                'db_table': 'pages_department',
                'permissions': (('trash_department', 'Can soft delete department'), ('restore_department', 'Can restore department')),
                'get_latest_by': 'update_date',
            },
            bases=('objects.page',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
