# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 17:56
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
        ('pages', '0003_auto_20171121_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Page')),
                ('title', models.CharField(max_length=200)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('summary', ckeditor.fields.RichTextField(blank=True, max_length=400, null=True)),
                ('pinned', models.BooleanField(default=False)),
                ('author_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'permissions': (('trash_news', 'Can soft delete news'), ('restore_news', 'Can restore news')),
                'verbose_name': 'News',
                'db_table': 'pages_news',
                'ordering': ['-author_date'],
                'get_latest_by': 'update_date',
                'verbose_name_plural': 'News',
            },
            bases=('objects.page',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NewsYear',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Page')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('yearend', models.CharField(blank=True, max_length=4, unique=True)),
            ],
            options={
                'permissions': (('trash_newsyear', 'Can soft delete newsyear'), ('restore_newsyear', 'Can restore newsyear')),
                'verbose_name': 'News Year',
                'db_table': 'pages_newsyear',
                'get_latest_by': 'update_date',
                'verbose_name_plural': 'News Years',
            },
            bases=('objects.page',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
