# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20171129_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='page_ptr',
            new_name='news_page_node',
        ),
        migrations.RenameField(
            model_name='newsyear',
            old_name='page_ptr',
            new_name='newsyear_page_node',
        ),
    ]
