# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_subpage_related_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='enrollment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='main_fax',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='main_phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='openenrollmentstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages_school_openenrollmentstatus', to='taxonomy.OpenEnrollmentStatus'),
        ),
        migrations.AlterField(
            model_name='school',
            name='website_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
