# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 18:59
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_node_has_permissions'),
        ('taxonomy', '0001_initial'),
        ('pages', '0010_auto_20171201_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Page')),
                ('title', models.CharField(db_index=True, max_length=200, unique=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('main_phone', models.CharField(max_length=11)),
                ('main_fax', models.CharField(max_length=11)),
                ('mission_statement', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Mission Statement')),
                ('vision_statement', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Vision Statement')),
                ('building_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages_board_building_location', to='taxonomy.Location')),
            ],
            options={
                'db_table': 'board_board',
                'verbose_name_plural': 'Board',
                'verbose_name': 'Board',
                'get_latest_by': 'update_date',
                'permissions': (('trash_board', 'Can soft delete board'), ('restore_board', 'Can restore board')),
            },
            bases=('objects.page',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
