# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 20:10
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_node_has_permissions'),
        ('taxonomy', '0003_boardmeetingtype'),
        ('pages', '0012_auto_20171202_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardSubPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Page')),
                ('title', models.CharField(db_index=True, max_length=200, unique=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('main_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('main_fax', models.CharField(blank=True, max_length=11, null=True)),
                ('building_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages_boardsubpage_building_location', to='taxonomy.Location')),
            ],
            options={
                'get_latest_by': 'update_date',
                'verbose_name_plural': 'Board Subpages',
                'verbose_name': 'Board Subpage',
                'db_table': 'pages_boardsubpage',
                'permissions': (('trash_boardsubpage', 'Can soft delete board subpage'), ('restore_boardsubpage', 'Can restore board subpage')),
            },
            bases=('objects.page',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='subpage',
            options={'get_latest_by': 'update_date', 'permissions': (('trash_subpage', 'Can soft delete subpage'), ('restore_subpage', 'Can restore subpage')), 'verbose_name': 'Subpage', 'verbose_name_plural': 'Subpages'},
        ),
        migrations.AlterModelTable(
            name='board',
            table='pages_board',
        ),
    ]
