# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20171204_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardsubpage',
            name='building_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages_boardsubpage_building_location', to='taxonomy.Location'),
        ),
    ]
