# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20171204_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='page_ptr',
            field=models.OneToOneField(db_column='board_page_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Page'),
        ),
        migrations.AlterField(
            model_name='boardsubpage',
            name='page_ptr',
            field=models.OneToOneField(db_column='boardsubpage_page_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Page'),
        ),
    ]
