# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20171204_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='page_ptr',
            new_name='board_page_node',
        ),
        migrations.RenameField(
            model_name='boardsubpage',
            old_name='page_ptr',
            new_name='boardsubpage_page_node',
        ),
    ]
