# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_node_has_permissions'),
        ('pages', '0016_auto_20171204_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardsubpage',
            name='related_node',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages_boardsubpage_node', to='objects.Node'),
        ),
    ]
