# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_event'),
        ('pages', '0017_boardsubpage_related_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMeetingYear',
            fields=[
                ('title', models.CharField(max_length=200, unique=True)),
                ('yearend', models.CharField(blank=True, max_length=4, unique=True)),
                ('boardmeetingyear_page_node', models.OneToOneField(db_column='boardmeetingyear_page_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Page')),
            ],
            options={
                'verbose_name': 'Board Meeting Year',
                'permissions': (('trash_boardmeetingyear', 'Can soft delete board meeting year'), ('restore_boardmeetingyear', 'Can restore board meeting year')),
                'get_latest_by': 'update_date',
                'db_table': 'pages_boardmeetingyear',
                'verbose_name_plural': 'Board Meeting Years',
            },
            bases=('objects.page',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
