# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 19:47
from __future__ import unicode_literals

from django.db import migrations, models

def set_inline_order(apps,schema_editor):
    Model = apps.get_model('pages','subpage')
    for index, item in enumerate(Model.objects.all()):
        print('Setting ' + item.title + ' to an index of ' + str(index + 1))
        item.inline_order = index + 1
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_boardmeetingyear'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subpage',
            options={'get_latest_by': 'update_date', 'ordering': ['inline_order'], 'permissions': (('trash_subpage', 'Can soft delete subpage'), ('restore_subpage', 'Can restore subpage')), 'verbose_name': 'Subpage', 'verbose_name_plural': 'Subpages'},
        ),
        migrations.AddField(
            model_name='subpage',
            name='inline_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(set_inline_order),
    ]
