# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20171214_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardsubpage',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_boardsubpage', 'Can soft delete board subpage'), ('restore_boardsubpage', 'Can restore board subpage')), 'verbose_name': 'Board Subpage', 'verbose_name_plural': 'Board Subpages'},
        ),
        migrations.AlterModelOptions(
            name='subpage',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'ordering': ['inline_order'], 'permissions': (('trash_subpage', 'Can soft delete subpage'), ('restore_subpage', 'Can restore subpage')), 'verbose_name': 'Subpage', 'verbose_name_plural': 'Subpages'},
        ),
        migrations.AlterModelManagers(
            name='boardsubpage',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='subpage',
            managers=[
            ],
        ),
    ]
