# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20171214_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_board', 'Can soft delete board'), ('restore_board', 'Can restore board')), 'verbose_name': 'Board', 'verbose_name_plural': 'Board'},
        ),
        migrations.AlterModelOptions(
            name='boardmeetingyear',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_boardmeetingyear', 'Can soft delete board meeting year'), ('restore_boardmeetingyear', 'Can restore board meeting year')), 'verbose_name': 'Board Meeting Year', 'verbose_name_plural': 'Board Meeting Years'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_department', 'Can soft delete department'), ('restore_department', 'Can restore department')), 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'ordering': ['-author_date'], 'permissions': (('trash_news', 'Can soft delete news'), ('restore_news', 'Can restore news')), 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='newsyear',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_newsyear', 'Can soft delete newsyear'), ('restore_newsyear', 'Can restore newsyear')), 'verbose_name': 'News Year', 'verbose_name_plural': 'News Years'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_page', 'Can soft delete page'), ('restore_page', 'Can restore page')), 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_school', 'Can soft delete school'), ('restore_school', 'Can restore school')), 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterModelManagers(
            name='board',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='boardmeetingyear',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='department',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='news',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='newsyear',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='page',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='school',
            managers=[
            ],
        ),
    ]
