# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_faq'),
        ('pages', '0024_department_is_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictCalendarYear',
            fields=[
                ('title', models.CharField(max_length=200, unique=True)),
                ('yearend', models.CharField(blank=True, max_length=4, unique=True)),
                ('districtcalendaryear_page_node', models.OneToOneField(db_column='districtcalendaryear_page_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Page')),
            ],
            options={
                'default_manager_name': 'objects',
                'db_table': 'pages_districtcalendaryear',
                'verbose_name': 'District Calendar Year',
                'verbose_name_plural': 'District Calendar Years',
                'permissions': (('trash_districtcalendaryear', 'Can soft delete district calendar year'), ('restore_districtcalendaryear', 'Can restore district calendar year')),
                'get_latest_by': 'update_date',
            },
            bases=('objects.page',),
        ),
    ]
