# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 19:56
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_contactmessage'),
        ('pages', '0026_school_calendar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperintendentMessage',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('summary', ckeditor.fields.RichTextField(blank=True, max_length=400, null=True)),
                ('author_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('superintendentmessage_page_node', models.OneToOneField(db_column='superintendentmessage_page_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Page')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages_superintendentmessage_node', to='objects.Node')),
            ],
            options={
                'db_table': 'pages_superintendentmessage',
                'default_manager_name': 'objects',
                'verbose_name_plural': 'Superintendent Messages',
                'ordering': ['-author_date'],
                'verbose_name': 'Superintendent Message',
                'permissions': (('trash_superintendentmessage', 'Can soft delete superintendent message'), ('restore_superintendentmessage', 'Can restore superintendent message')),
                'get_latest_by': 'update_date',
            },
            bases=('objects.page',),
        ),
        migrations.CreateModel(
            name='SuperintendentMessageYear',
            fields=[
                ('title', models.CharField(max_length=200, unique=True)),
                ('yearend', models.CharField(blank=True, max_length=4, unique=True)),
                ('superintendentmessageyear_page_node', models.OneToOneField(db_column='superintendentmessage_page_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Page')),
            ],
            options={
                'db_table': 'pages_superintendentmessageyear',
                'default_manager_name': 'objects',
                'verbose_name_plural': 'Superintendent Message Years',
                'verbose_name': 'Superintendent Message Year',
                'permissions': (('trash_superintendentmessageyear', 'Can soft delete superintendent message year'), ('restore_superintendentmessageyear', 'Can restore superintendent message year')),
                'get_latest_by': 'update_date',
            },
            bases=('objects.page',),
        ),
    ]
