# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0008_schooloption'),
        ('pages', '0029_auto_20180110_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='schooloptions',
            field=models.ManyToManyField(blank=True, related_name='pages_school_schooloptions', to='taxonomy.SchoolOption', verbose_name='School Options'),
        ),
    ]
