# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 17:13
from __future__ import unicode_literals

from django.db import migrations


def set_schooladmin_order(apps, schema_editor):
    School = apps.get_model('pages', 'school')
    for school in School.objects.all():
        count = 1
        for entry in school.directoryentries_schooladministrator_node.order_by(
            'schooladministratortype__lft',
            'employee__first_name',
        ):
            print('Setting {0} {1} to position {2} for {3}'.format(
                entry.employee.first_name,
                entry.employee.last_name,
                count,
                school.title,
                ))
            entry.inline_order = count
            entry.save()
            count += 1


class Migration(migrations.Migration):

    dependencies = [
        ('directoryentries', '0015_auto_20180205_1603'),
        ('pages', '0030_school_schooloptions'),
    ]

    operations = [
        migrations.RunPython(set_schooladmin_order)
    ]
