# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-01 14:55
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_school_school_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
    ]
