# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-10 15:40
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_auto_20180501_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superintendentmessage',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
    ]
