# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-02 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_auto_20180510_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtcalendaryear',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='districtcalendaryear',
            name='yearend',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
