# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-24 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'ordering': ['inline_order'], 'permissions': (('trash_page', 'Can soft delete page'), ('restore_page', 'Can restore page')), 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AddField(
            model_name='page',
            name='inline_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
