# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-28 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_auto_20180824_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='school_employees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_about_our_school', to='pages.Page'),
        ),
    ]
