# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-28 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_page_school_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='school_employees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_school_employees', to='pages.Page', verbose_name='District Website Employees Page'),
        ),
    ]
