# Generated by Django 2.0 on 2018-08-30 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_auto_20180828_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='building_location',
            field=models.ForeignKey(limit_choices_to={'deleted': False}, on_delete=django.db.models.deletion.PROTECT, related_name='pages_board_building_location', to='taxonomy.Location'),
        ),
        migrations.AlterField(
            model_name='boardsubpage',
            name='building_location',
            field=models.ForeignKey(blank=True, limit_choices_to={'deleted': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages_boardsubpage_building_location', to='taxonomy.Location'),
        ),
        migrations.AlterField(
            model_name='department',
            name='building_location',
            field=models.ForeignKey(limit_choices_to={'deleted': False}, on_delete=django.db.models.deletion.PROTECT, related_name='pages_department_building_location', to='taxonomy.Location'),
        ),
        migrations.AlterField(
            model_name='page',
            name='about_our_school',
            field=models.ForeignKey(limit_choices_to={'deleted': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_about_our_school', to='pages.School'),
        ),
        migrations.AlterField(
            model_name='page',
            name='school_employees',
            field=models.ForeignKey(limit_choices_to={'deleted': 0, 'published': 1, 'site__domain': 'www.slcschools.org', 'url': '/employees/'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_school_employees', to='pages.Page', verbose_name='District Website Employees Page'),
        ),
        migrations.AlterField(
            model_name='school',
            name='building_location',
            field=models.ForeignKey(limit_choices_to={'deleted': False}, on_delete=django.db.models.deletion.PROTECT, related_name='pages_school_building_location', to='taxonomy.Location'),
        ),
        migrations.AlterField(
            model_name='school',
            name='openenrollmentstatus',
            field=models.ForeignKey(blank=True, limit_choices_to={'deleted': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages_school_openenrollmentstatus', to='taxonomy.OpenEnrollmentStatus'),
        ),
        migrations.AlterField(
            model_name='school',
            name='schooltype',
            field=models.ForeignKey(limit_choices_to={'deleted': False}, on_delete=django.db.models.deletion.PROTECT, related_name='pages_school_schooltype', to='taxonomy.SchoolType'),
        ),
        migrations.AlterField(
            model_name='subpage',
            name='building_location',
            field=models.ForeignKey(blank=True, limit_choices_to={'deleted': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages_subpage_building_location', to='taxonomy.Location'),
        ),
    ]
