# Generated by Django 2.0 on 2018-09-18 16:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_auto_20180830_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'ordering': ['inline_order'], 'permissions': (('trash_announcement', 'Can soft delete announcement'), ('restore_announcement', 'Can restore announcement')), 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='board',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'permissions': (('trash_board', 'Can soft delete board'), ('restore_board', 'Can restore board')), 'verbose_name': 'Board', 'verbose_name_plural': 'Board'},
        ),
        migrations.AlterModelOptions(
            name='boardmeetingyear',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'permissions': (('trash_boardmeetingyear', 'Can soft delete board meeting year'), ('restore_boardmeetingyear', 'Can restore board meeting year')), 'verbose_name': 'Board Meeting Year', 'verbose_name_plural': 'Board Meeting Years'},
        ),
        migrations.AlterModelOptions(
            name='boardsubpage',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'ordering': ['inline_order'], 'permissions': (('trash_boardsubpage', 'Can soft delete board subpage'), ('restore_boardsubpage', 'Can restore board subpage')), 'verbose_name': 'Board Subpage', 'verbose_name_plural': 'Board Subpages'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'permissions': (('trash_department', 'Can soft delete department'), ('restore_department', 'Can restore department')), 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='districtcalendaryear',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'permissions': (('trash_districtcalendaryear', 'Can soft delete district calendar year'), ('restore_districtcalendaryear', 'Can restore district calendar year')), 'verbose_name': 'District Calendar Year', 'verbose_name_plural': 'District Calendar Years'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'ordering': ['-author_date'], 'permissions': (('trash_news', 'Can soft delete news'), ('restore_news', 'Can restore news')), 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='newsyear',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'permissions': (('trash_newsyear', 'Can soft delete newsyear'), ('restore_newsyear', 'Can restore newsyear')), 'verbose_name': 'News Year', 'verbose_name_plural': 'News Years'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'ordering': ['inline_order'], 'permissions': (('trash_page', 'Can soft delete page'), ('restore_page', 'Can restore page')), 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'permissions': (('trash_school', 'Can soft delete school'), ('restore_school', 'Can restore school')), 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterModelOptions(
            name='subpage',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'ordering': ['inline_order'], 'permissions': (('trash_subpage', 'Can soft delete subpage'), ('restore_subpage', 'Can restore subpage')), 'verbose_name': 'Subpage', 'verbose_name_plural': 'Subpages'},
        ),
        migrations.AlterModelOptions(
            name='superintendentmessage',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'ordering': ['-author_date'], 'permissions': (('trash_superintendentmessage', 'Can soft delete superintendent message'), ('restore_superintendentmessage', 'Can restore superintendent message')), 'verbose_name': 'Superintendent Message', 'verbose_name_plural': 'Superintendent Messages'},
        ),
        migrations.AlterModelOptions(
            name='superintendentmessageyear',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'permissions': (('trash_superintendentmessageyear', 'Can soft delete superintendent message year'), ('restore_superintendentmessageyear', 'Can restore superintendent message year')), 'verbose_name': 'Superintendent Message Year', 'verbose_name_plural': 'Superintendent Message Years'},
        ),
        migrations.AlterModelManagers(
            name='announcement',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='board',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='boardmeetingyear',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='boardsubpage',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='department',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='districtcalendaryear',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='news',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='newsyear',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='page',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='school',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='subpage',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='superintendentmessage',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='superintendentmessageyear',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
