# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='primary_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objects_node_primary_contact', to=settings.AUTH_USER_MODEL, to_field='uuid'),
        ),
    ]
