# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_node_primary_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='has_permissions',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
