# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_node_has_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_type', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('event_node', models.OneToOneField(db_column='event_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Node')),
            ],
            options={
                'get_latest_by': 'create_date',
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'objects_event',
            },
            bases=('objects.node',),
        ),
    ]
