# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_event'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='node',
            unique_together=set([]),
        ),
    ]
