# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_auto_20171210_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directoryentry',
            options={'default_manager_name': 'objects', 'get_latest_by': 'create_date', 'verbose_name': 'Directory Entry', 'verbose_name_plural': 'Directory Entries'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'default_manager_name': 'objects', 'get_latest_by': 'create_date', 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'default_manager_name': 'objects', 'get_latest_by': 'create_date', 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'default_manager_name': 'objects', 'get_latest_by': 'create_date', 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'default_manager_name': 'objects', 'get_latest_by': 'create_date', 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'default_manager_name': 'objects', 'get_latest_by': 'create_date', 'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'default_manager_name': 'objects', 'get_latest_by': 'create_date', 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='taxonomy',
            options={'default_manager_name': 'objects', 'get_latest_by': 'create_date', 'verbose_name': 'Taxonomy', 'verbose_name_plural': 'Taxonomies'},
        ),
    ]
