# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_auto_20171214_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('faq_type', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('faq_node', models.OneToOneField(db_column='faq_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Node')),
            ],
            options={
                'verbose_name_plural': 'FAQs',
                'db_table': 'objects_faq',
                'default_manager_name': 'objects',
                'get_latest_by': 'create_date',
                'verbose_name': 'FAQ',
            },
            bases=('objects.node',),
        ),
    ]
