# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='searchable',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
