# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 20:50
from __future__ import unicode_literals

import apps.common.functions
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_node_searchable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='primary_contact',
            field=models.ForeignKey(default=apps.common.functions.get_webmaster, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objects_node_primary_contact', to=settings.AUTH_USER_MODEL, to_field='uuid'),
        ),
    ]
