# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_node_searchable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('contactmessagae_type', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('contactmessage_node', models.OneToOneField(db_column='contactmessage_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Node')),
            ],
            options={
                'db_table': 'objects_contactmessage',
                'verbose_name_plural': 'Contact Messages',
                'get_latest_by': 'create_date',
                'default_manager_name': 'objects',
                'verbose_name': 'Contact Message',
            },
            bases=('objects.node',),
        ),
    ]
