# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def change_default_site(apps, schema_editor):
    Site = apps.get_model('sites','Site')
    Alias = apps.get_model('multisite','Alias')
    site = Site.objects.get(pk=1)
    site.domain = 'www.slcschools.org'
    site.name = 'District Website'
    site.save()
    alias = site.aliases.first()
    alias.domain = 'www.slcschools.org'
    alias, created = Alias.objects.get_or_create(domain='slcschools.org',is_canonical=None,redirect_to_canonical=True,site=site)
    alias.save()
    alias, created = Alias.objects.get_or_create(domain='www-test.slcschools.org',is_canonical=None,redirect_to_canonical=False,site=site)
    alias.save()
    alias, created = Alias.objects.get_or_create(domain='www-dev.slcschools.org',is_canonical=None,redirect_to_canonical=False,site=site)
    alias.save()


def set_default_site(apps, schema_editor):
    Node = apps.get_model('objects','node')
    Site = apps.get_model('sites','site')
    site = Site.objects.get(pk=1)
    for node in Node.objects.all():
        print('Setting ' + node.node_title + ' to be on site: ' + site.name) 
        node.site = site
        node.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('objects', '0009_contactmessage'),
    ]

    operations = [
        migrations.RunPython(change_default_site),
        migrations.AddField(
            model_name='node',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.RunPython(set_default_site),
    ]
