# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_auto_20180123_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='contactmessagae_type',
        ),
        migrations.RemoveField(
            model_name='directoryentry',
            name='directoryentry_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='faq_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='link',
            name='link_type',
        ),
        migrations.RemoveField(
            model_name='page',
            name='page_type',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='taxonomy_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
