# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 21:53
from __future__ import unicode_literals

from django.db import migrations
import apps.common.functions as commonfunctions


def saveall(apps, schema_editor):
    Node = apps.get_model('objects','node')
    for node in Node.objects.all().order_by('level'):
        object = commonfunctions.nodefindobject(node)
        object.save()

class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0014_node_slug'),
        ('users', '0005_auto_20180125_2233'),
    ]

    operations = [
        migrations.RunPython(saveall),
    ]
