# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 19:26
from __future__ import unicode_literals

import apps.common.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_pagelayout'),
        ('objects', '0015_data_slug_sluginstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='pagelayout',
            field=models.ForeignKey(default=apps.common.functions.get_default_pagelayout, on_delete=django.db.models.deletion.PROTECT, to='dashboard.PageLayout'),
        ),
    ]
