# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-18 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_initial_pagelayouts'),
        ('objects', '0015_data_slug_sluginstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='pagelayout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.PageLayout'),
        ),
    ]
