# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 19:49
from __future__ import unicode_literals

import apps.common.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0017_auto_20180418_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='pagelayout',
            field=models.ForeignKey(default=apps.common.functions.get_default_pagelayout, on_delete=django.db.models.deletion.PROTECT, to='dashboard.PageLayout'),
        ),
    ]
