# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-02 15:19
from __future__ import unicode_literals

import apps.common.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_generalsettings_sitetype'),
        ('objects', '0018_auto_20180419_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='requiredpage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects_node_requiredpage', to='dashboard.SiteTypeRequiredPage'),
        ),
        migrations.AlterField(
            model_name='node',
            name='pagelayout',
            field=models.ForeignKey(default=apps.common.functions.get_default_pagelayout, on_delete=django.db.models.deletion.PROTECT, related_name='objects_node_pagelayout', to='dashboard.PageLayout'),
        ),
    ]
