# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-27 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0020_auto_20180711_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='section_page_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
