# Generated by Django 2.0 on 2018-08-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0021_node_section_page_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
