# Generated by Django 2.0 on 2018-08-30 20:05

import apps.common.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0022_auto_20180830_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='site',
            field=models.ForeignKey(default=apps.common.functions.get_management_website, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
