# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_node_has_permissions'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPrecinct',
            fields=[
                ('title', models.CharField(max_length=200, unique=True)),
                ('boardprecinct_taxonomy_node', models.OneToOneField(db_column='boardprecinct_taxonomy_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy')),
            ],
            options={
                'verbose_name_plural': 'Board Precincts',
                'get_latest_by': 'update_date',
                'permissions': (('trash_boardprecinct', 'Can soft delete board precinct'), ('restore_boardprecinct', 'Can restore board precinct')),
                'default_manager_name': 'objects',
                'db_table': 'taxonomy_boardprecinct',
                'verbose_name': 'Board Precinct',
            },
            bases=('objects.taxonomy',),
        ),
    ]
