# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_node_has_permissions'),
        ('taxonomy', '0002_boardprecinct'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMeetingType',
            fields=[
                ('title', models.CharField(max_length=200, unique=True)),
                ('boardmeetingtype_taxonomy_node', models.OneToOneField(db_column='boardmeetingtype_taxonomy_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy')),
            ],
            options={
                'db_table': 'taxonomy_boardmeetingtype',
                'verbose_name': 'Board Meeting Type',
                'get_latest_by': 'update_date',
                'permissions': (('trash_boardmeetingtype', 'Can soft delete board meeting type'), ('restore_boardprecinct', 'Can restore board meeting type')),
                'verbose_name_plural': 'Board Meeting Types',
                'default_manager_name': 'objects',
            },
            bases=('objects.taxonomy',),
        ),
    ]
