# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_boardpolicysection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_city', 'Can soft delete city'), ('restore_city', 'Can restore city')), 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_language', 'Can soft delete language'), ('restore_language', 'Can restore language')), 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_location', 'Can soft delete location'), ('restore_location', 'Can restore location')), 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='openenrollmentstatus',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_openenrollmentstatus', 'Can soft delete school open enrollment status'), ('restore_openenrollmentstatus', 'Can restore school open enrollment status')), 'verbose_name': 'Open Enrollment Status', 'verbose_name_plural': 'Open Enrollment Statuses'},
        ),
        migrations.AlterModelOptions(
            name='schooladministratortype',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_schooladministratortype', 'Can soft delete school administrator type'), ('restore_schooladministratortype', 'Can restore school administrator type')), 'verbose_name': 'School Administrator Type', 'verbose_name_plural': 'School Administrator Types'},
        ),
        migrations.AlterModelOptions(
            name='schooltype',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_schooltype', 'Can soft delete school type'), ('restore_schooltype', 'Can restore school type')), 'verbose_name': 'School Type', 'verbose_name_plural': 'School Types'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_state', 'Can soft delete state'), ('restore_state', 'Can restore state')), 'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.AlterModelOptions(
            name='translationtype',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_translationtype', 'Can soft delete translation type'), ('restore_translationtype', 'Can restore translation type')), 'verbose_name': 'Translation Type', 'verbose_name_plural': 'Translation Types'},
        ),
        migrations.AlterModelOptions(
            name='zipcode',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_zipcode', 'Can soft delete zipcode'), ('restore_zipcode', 'Can restore zipcode')), 'verbose_name': 'ZIP Code', 'verbose_name_plural': 'ZIP Codes'},
        ),
        migrations.AlterModelManagers(
            name='city',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='language',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='location',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='openenrollmentstatus',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='schooladministratortype',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='schooltype',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='state',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='translationtype',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='zipcode',
            managers=[
            ],
        ),
    ]
