# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_faq'),
        ('taxonomy', '0005_auto_20171214_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictCalendarEventCategory',
            fields=[
                ('title', models.CharField(max_length=200, unique=True, verbose_name='District Calendar Event Category')),
                ('css_class', models.CharField(max_length=100, verbose_name='CSS Class used on events of this type')),
                ('districtcalendareventcategory_taxonomy_node', models.OneToOneField(db_column='districtcalendareventcategory_taxonomy_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy')),
            ],
            options={
                'verbose_name': 'District Calendar Event Category',
                'default_manager_name': 'objects',
                'permissions': (('trash_districtcalendareventcategory', 'Can soft delete district calendar event category'), ('restore_districtcalendareventcategory', 'Can restore district calendar event category')),
                'db_table': 'taxonomy_districtcalendareventcategory',
                'get_latest_by': 'update_date',
                'verbose_name_plural': 'District Calendar Event Categories',
            },
            bases=('objects.taxonomy',),
        ),
    ]
