# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_faq'),
        ('taxonomy', '0006_districtcalendareventcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictLogoGroup',
            fields=[
                ('title', models.CharField(max_length=200, unique=True, verbose_name='District Logo Group')),
                ('districtlogogroup_taxonomy_node', models.OneToOneField(db_column='districtlogogroup_taxonomy_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy')),
            ],
            options={
                'verbose_name_plural': 'District Logo Groups',
                'db_table': 'taxonomy_districtlogogroup',
                'default_manager_name': 'objects',
                'verbose_name': 'District Logo Group',
                'get_latest_by': 'update_date',
                'permissions': (('trash_districtlogogroup', 'Can soft delete district logo group'), ('restore_districtlogogroup', 'Can restore district logo group')),
            },
            bases=('objects.taxonomy',),
        ),
        migrations.CreateModel(
            name='DistrictLogoStyleVariation',
            fields=[
                ('title', models.CharField(max_length=200, unique=True, verbose_name='District Logo Style Variation')),
                ('districtlogostylevariation_taxonomy_node', models.OneToOneField(db_column='districtlogostylevariation_taxonomy_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy')),
            ],
            options={
                'verbose_name_plural': 'District Logo Style Variations',
                'db_table': 'taxonomy_districtlogostylevariation',
                'default_manager_name': 'objects',
                'verbose_name': 'District Logo Style Variation',
                'get_latest_by': 'update_date',
                'permissions': (('trash_districtlogostylevariation', 'Can soft delete district logo style variation'), ('restore_districtlogostylevariation', 'Can restore district logo style variation')),
            },
            bases=('objects.taxonomy',),
        ),
    ]
