# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_contactmessage'),
        ('taxonomy', '0007_districtlogogroup_districtlogostylevariation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolOption',
            fields=[
                ('title', models.CharField(max_length=200, unique=True, verbose_name='School Option')),
                ('schooloption_taxonomy_node', models.OneToOneField(db_column='schooloption_taxonomy_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy')),
            ],
            options={
                'permissions': (('trash_schooloption', 'Can soft delete school option'), ('restore_schooloption', 'Can restore school option')),
                'default_manager_name': 'objects',
                'verbose_name': 'School Option',
                'db_table': 'taxonomy_schooloption',
                'verbose_name_plural': 'School Options',
                'get_latest_by': 'update_date',
            },
            bases=('objects.taxonomy',),
        ),
    ]
