# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 21:51
from __future__ import unicode_literals

import apps.common.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0008_schooloption'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardprecinct',
            name='precinct_map',
            field=models.FileField(blank=True, help_text='Upload a PDF file that represent the boundaries of this precinct.', max_length=2000, null=True, upload_to=apps.common.functions.precinct_map_upload_to, verbose_name='Precinct Map'),
        ),
    ]
