# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-25 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0009_boardprecinct_precinct_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardprecinct',
            name='precinct_map',
        ),
    ]
