# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-26 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0010_remove_boardprecinct_precinct_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='iso_639_1_language_code',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='ISO 639-1 Language Code'),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_code',
            field=models.CharField(max_length=5, unique=True, verbose_name='Google Language Code'),
        ),
    ]
