# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-22 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0020_auto_20180711_0613'),
        ('taxonomy', '0011_auto_20180626_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectGradeLevel',
            fields=[
                ('title', models.CharField(db_index=True, max_length=200)),
                ('subjectgradelevel_taxonomy_node', models.OneToOneField(db_column='subjectgradelevel_taxonomy_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy')),
                ('inline_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_subjectgradelevel_node', to='objects.Node')),
            ],
            options={
                'permissions': (('trash_subjectgradelevel', 'Can soft delete Subject or Grade Level'), ('restore_subjectgradelevel', 'Can restore Subject or Grade Level')),
                'ordering': ['inline_order'],
                'verbose_name': 'Subject or Grade Level',
                'default_manager_name': 'objects',
                'db_table': 'taxonomy_subjectgradelevel',
                'verbose_name_plural': 'Subjects and Grade Levels',
                'get_latest_by': 'update_date',
            },
            bases=('objects.taxonomy',),
        ),
    ]
