# Generated by Django 2.0 on 2018-08-30 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0012_subjectgradelevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_translationtype',
            field=models.ForeignKey(db_column='translationtype', limit_choices_to={'deleted': False}, on_delete=django.db.models.deletion.PROTECT, related_name='taxonomy_language_translationtype', to='taxonomy.TranslationType', verbose_name='Translation Type'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_city',
            field=models.ForeignKey(db_column='city', limit_choices_to={'deleted': False}, on_delete=django.db.models.deletion.PROTECT, related_name='taxonomy_location_city', to='taxonomy.City'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_state',
            field=models.ForeignKey(db_column='state', limit_choices_to={'deleted': False}, on_delete=django.db.models.deletion.PROTECT, related_name='taxonomy_location_state', to='taxonomy.State'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_zipcode',
            field=models.ForeignKey(db_column='zipcode', limit_choices_to={'deleted': False}, on_delete=django.db.models.deletion.PROTECT, related_name='taxonomy_location_zipcode', to='taxonomy.Zipcode'),
        ),
    ]
