# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:29
from __future__ import unicode_literals

import apps.common.functions
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('file_file', models.FileField(max_length=2000, upload_to=apps.common.functions.file_upload_to, verbose_name='File')),
                ('file_file_node', models.OneToOneField(db_column='file_file_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.File')),
                ('file_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files_file_file_language', to='taxonomy.Language')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_file_node', to='objects.Node')),
            ],
            options={
                'verbose_name_plural': 'Files',
                'db_table': 'files_file',
                'verbose_name': 'File',
                'permissions': (('trash_file', 'Can soft delete file'), ('restore_file', 'Can restore file')),
                'get_latest_by': 'update_date',
            },
            bases=('objects.file',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
