# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 17:04
from __future__ import unicode_literals

import apps.common.functions
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_auto_20171210_1447'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('file_file', models.FileField(max_length=2000, upload_to=apps.common.functions.file_upload_to, verbose_name='File')),
                ('audiofile_file_node', models.OneToOneField(db_column='audiofile_file_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.File')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_audiofile_node', to='objects.Node')),
            ],
            options={
                'permissions': (('trash_audiofile', 'Can soft delete audio file'), ('restore_audiofile', 'Can restore audio file')),
                'verbose_name_plural': 'Audio Files',
                'db_table': 'files_audiofile',
                'get_latest_by': 'update_date',
                'verbose_name': 'Audio File',
            },
            bases=('objects.file',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('file_file', models.FileField(max_length=2000, upload_to=apps.common.functions.file_upload_to, verbose_name='File')),
                ('videofile_file_node', models.OneToOneField(db_column='videofile_file_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.File')),
                ('related_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_videofile_node', to='objects.Node')),
            ],
            options={
                'permissions': (('trash_videofile', 'Can soft delete video file'), ('restore_videofile', 'Can restore video file')),
                'verbose_name_plural': 'Video Files',
                'db_table': 'files_videofile',
                'get_latest_by': 'update_date',
                'verbose_name': 'Video File',
            },
            bases=('objects.file',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
