# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_audiofile_videofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiofile',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_audiofile', 'Can soft delete audio file'), ('restore_audiofile', 'Can restore audio file')), 'verbose_name': 'Audio File', 'verbose_name_plural': 'Audio Files'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_file', 'Can soft delete file'), ('restore_file', 'Can restore file')), 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='videofile',
            options={'default_manager_name': 'objects', 'get_latest_by': 'update_date', 'permissions': (('trash_videofile', 'Can soft delete video file'), ('restore_videofile', 'Can restore video file')), 'verbose_name': 'Video File', 'verbose_name_plural': 'Video Files'},
        ),
        migrations.AlterModelManagers(
            name='audiofile',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='file',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='videofile',
            managers=[
            ],
        ),
    ]
