# Generated by Django 2.0 on 2018-09-18 16:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20180830_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiofile',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'permissions': (('trash_audiofile', 'Can soft delete audio file'), ('restore_audiofile', 'Can restore audio file')), 'verbose_name': 'Audio File', 'verbose_name_plural': 'Audio Files'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'permissions': (('trash_file', 'Can soft delete file'), ('restore_file', 'Can restore file')), 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='precinctmap',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'permissions': (('trash_precinctmap', 'Can soft delete precinct map'), ('restore_file', 'Can restore precinct map')), 'verbose_name': 'Precinct Map', 'verbose_name_plural': 'Precinct Maps'},
        ),
        migrations.AlterModelOptions(
            name='videofile',
            options={'default_manager_name': 'base_manager', 'get_latest_by': 'update_date', 'permissions': (('trash_videofile', 'Can soft delete video file'), ('restore_videofile', 'Can restore video file')), 'verbose_name': 'Video File', 'verbose_name_plural': 'Video Files'},
        ),
        migrations.AlterModelManagers(
            name='audiofile',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='file',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='precinctmap',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='videofile',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
